apiVersion: v1
data:
  channel: c3Rha2F0ZXItcGxhdGZvcm0tYWtzLWFsZXJ0cw==
  webHookURL: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDZQNVBTMlY4L0JTNTVORFpVUC9nbHJTQ3ZQN0Q1cEl1ckFFMWpJUzNHSXo=
kind: Secret
metadata:
  name: slack-notification-hook
  namespace: delivery
type: Opaque