# pipeline base image
image:
  name: stakater/builder-tool:terraform-0.12.7-v0.0.10

# Configuring CI/CD environment variables
variables:
  # Underlying cloud vars
  # CLOUD_PROVIDER: "CLOUD_PROVIDER"
  # KUBE_CONFIG: "KUBE_CONFIG"
  
  # # Repository vars
  STAKATER_PLATFORM_SSH_GIT_URL: "STAKATER_PLATFORM_SSH_GIT_URL"
  STAKATER_PLATFORM_BRANCH: "master"
  # USER_MAIL: "USER_MAIL"
  # USER_NAME: "USER_NAME"
  # REPO_ACCESS_TOKEN: "REPO_ACCESS_TOKEN"
  
  # # AWS credentials for external-dns
  # BASE64_ENCODED_AWS_ACCESS_KEY_ID: "BASE64_ENCODED_AWS_ACCESS_KEY_ID"
  # BASE64_ENCODED_AWS_SECRET_ACCESS_KEY: "BASE64_ENCODED_AWS_SECRET_ACCESS_KEY"

  # # Domain to configure on e.g. stakater.com
  # DOMAIN: "DOMAIN"

  # # Make Target
  # TARGET: "TARGET"
  
  # # Control: IngressMonitorController
  # BASE64_ENCODED_IMC_CONFIG: "BASE64_ENCODED_IMC_CONFIG"

  # # Delivery: Jenkins
  # BASE64_ENCODED_JENKINS_CFG: "BASE64_ENCODED_JENKINS_CFG"
  # KEYCLOAK_CLIENT_ID: "KEYCLOAK_CLIENT_ID"
  # KEYCLOAK_CLIENT_SECRET: "KEYCLOAK_CLIENT_SECRET"
  # BASE64_ENCODED_SLACK_CHANNEL: "BASE64_ENCODED_SLACK_CHANNEL"
  # BASE64_ENCODED_SLACK_WEBHOOK_URL: "BASE64_ENCODED_SLACK_WEBHOOK_URL"
  # BASE64_ENCODED_HUB_TOKEN: "BASE64_ENCODED_HUB_TOKEN"
  # BASE64_ENCODED_GITLAB_TOKEN: "BASE64_ENCODED_GITLAB_TOKEN"
  # BASE64_ENCODED_BITBUCKET_TOKEN: "BASE64_ENCODED_BITBUCKET_TOKEN"

  # Delivery: Nexus
  BASE64_ENCODED_NEXUS_ADMIN_ACCOUNT_JSON: "eyJuYW1lIjogInVzZXItYWRtaW4iLCJ0eXBlIjogImdyb292eSIsImNvbnRlbnQiOiAic2VjdXJpdHkuYWRkVXNlcigndXNlci1hZG1pbicsICdTdGFja2F0b3InLCAnQWRtaW4nLCAndXNlckBnbWFpbC5jb20nLCB0cnVlLCAnc3Rha2F0ZXJAcXdlcnR5Nzg2JywgWydueC1hZG1pbiddKSJ9"
  BASE64_ENCODED_NEXUS_CLUSTER_ACCOUNT_JSON: "eyJuYW1lIjogImNsdXN0ZXItYWRtaW4iLCJ0eXBlIjogImdyb292eSIsImNvbnRlbnQiOiAic2VjdXJpdHkuYWRkUm9sZSgnY2x1c3RlcicsICdjbHVzdGVyJywgJ1VzZXIgd2l0aCBwcml2aWxlZ2VzIHRvIGFsbG93IHJlYWQgYWNjZXNzIHRvIHJlcG8gY29udGVudCBhbmQgaGVhbHRjaGVjaycsIFsnbngtaGVhbHRoY2hlY2stcmVhZCcsJ254LXJlcG9zaXRvcnktdmlldy1kb2NrZXItc3RhY2thdG9yLWRvY2tlci1icm93c2UnLCdueC1yZXBvc2l0b3J5LXZpZXctZG9ja2VyLXN0YWNrYXRvci1kb2NrZXItcmVhZCcsJ254LXNlYXJjaC1yZWFkJ10sICBbJ254LWFub255bW91cyddKTsgc2VjdXJpdHkuYWRkVXNlcignY2x1c3Rlci1hZG1pbicsICdDbHVzdGVyJywgJ0NsdXN0ZXInLCAndXNlckBnbWFpbC5jb20nLCB0cnVlLCAnc3Rha2F0ZXJAcXdlcnR5Nzg2JywgWydjbHVzdGVyJ10pIn0="
  NEXUS_ADMIN_ACCOUNT_USERNAME: "user-admin"
  NEXUS_CLUSTER_ACCOUNT_USERNAME: "cluster-admin"

  # # Monitoring: Alertmanager
  # BASE64_ENCODED_ALERTMANAGER_CONFIG: "BASE64_ENCODED_ALERTMANAGER_CONFIG"

  # # Security: KeyCloak
  # BASE64_ENCODED_KEYCLOAK_CONFIG: "BASE64_ENCODED_KEYCLOAK_CONFIG"
  
  # # Security: ProxyInjector
  # BASE64_ENCODED_PROXYINJECTOR_CONFIG: "BASE64_ENCODED_PROXYINJECTOR_CONFIG"


before_script:
  # Configuring kubernetes cluster access
  - echo "configuration kubernetes access in pipeline"
  - mkdir ~/.kube/
  - echo $KUBE_CONFIG | base64 -d > ~/.kube/config
  # Configure git access
  - git config --global user.email $USER_MAIL
  - git config --global user.name $USER_NAME
  # Source AWS Creds.
  - export AWS_ACCESS_KEY_ID=$(echo $BASE64_ENCODED_AWS_ACCESS_KEY_ID | base64 -d)
  - export AWS_SECRET_ACCESS_KEY=$(echo $BASE64_ENCODED_AWS_SECRET_ACCESS_KEY | base64 -d) 

# pipeline stages
stages:
  - execute

execute:
  stage: execute
  script:
    - if [ "$TARGET" == "destroy" ]; then
    -   make destroy
    - else
    -   git checkout $STAKATER_PLATFORM_BRANCH
    -   make setupvars CLOUD_PROVIDER=$CLOUD_PROVIDER STAKATER_PLATFORM_SSH_GIT_URL=$STAKATER_PLATFORM_SSH_GIT_URL STAKATER_PLATFORM_BRANCH=$STAKATER_PLATFORM_BRANCH DOMAIN=$DOMAIN BASE64_ENCODED_AWS_ACCESS_KEY_ID=$BASE64_ENCODED_AWS_ACCESS_KEY_ID BASE64_ENCODED_AWS_SECRET_ACCESS_KEY=$BASE64_ENCODED_AWS_SECRET_ACCESS_KEY BASE64_ENCODED_IMC_CONFIG=$BASE64_ENCODED_IMC_CONFIG BASE64_ENCODED_JENKINS_CFG=$BASE64_ENCODED_JENKINS_CFG KEYCLOAK_CLIENT_ID=$KEYCLOAK_CLIENT_ID KEYCLOAK_CLIENT_SECRET=$KEYCLOAK_CLIENT_SECRET BASE64_ENCODED_HUB_TOKEN=$BASE64_ENCODED_HUB_TOKEN BASE64_ENCODED_GITLAB_TOKEN=$BASE64_ENCODED_GITLAB_TOKEN BASE64_ENCODED_BITBUCKET_TOKEN=$BASE64_ENCODED_BITBUCKET_TOKEN BASE64_ENCODED_ADMIN_ACCOUNT_JSON=$BASE64_ENCODED_ADMIN_ACCOUNT_JSON BASE64_ENCODED_CLUSTER_ACCOUNT_JSON=$BASE64_ENCODED_CLUSTER_ACCOUNT_JSON NEXUS_ADMIN_ACCOUNT_USERNAME=$NEXUS_ADMIN_ACCOUNT_USERNAME NEXUS_CLUSTER_ACCOUNT_USERNAME=$NEXUS_CLUSTER_ACCOUNT_USERNAME BASE64_ENCODED_ALERTMANAGER_CONFIG=$BASE64_ENCODED_ALERTMANAGER_CONFIG BASE64_ENCODED_KEYCLOAK_CONFIG=$BASE64_ENCODED_KEYCLOAK_CONFIG BASE64_ENCODED_PROXYINJECTOR_CONFIG=$BASE64_ENCODED_PROXYINJECTOR_CONFIG BASE64_ENCODED_SLACK_CHANNEL=$BASE64_ENCODED_SLACK_CHANNEL BASE64_ENCODED_SLACK_WEBHOOK_URL=$BASE64_ENCODED_SLACK_WEBHOOK_URL
    -   git add .
    -   git commit -m "[skip ci] update vars for deployment" || true
    -   git push https://oauth2:$REPO_ACCESS_TOKEN@${CI_PROJECT_URL:8} $STAKATER_PLATFORM_BRANCH || true 
    -   make $TARGET
    - fi