# pipeline base image
image:
  name: stakater/builder-tool:terraform-0.12.7-v0.0.10

# Configuring CI/CD environment variables
variables:
  KUBE_CONFIG: "KUBE_CONFIG"
  REPO_ACCESS_TOKEN: "REPO_ACCESS_TOKEN"
  TARGET: "TARGET"
  USER_MAIL: "stakater@gmail.com"
  USER_NAME: "stakater-user"


before_script:
  # Configuring kubernetes cluster access
  - echo "configuration kubernetes access in pipeline"
  - mkdir ~/.kube/
  - echo $KUBE_CONFIG | base64 -d > ~/.kube/config
  - export KUBECONFIG=~/.kube/config
  # Configure git access
  - git remote set-url origin https://$USER_NAME:$REPO_ACCESS_TOKEN@${CI_PROJECT_URL:8}
  - git config --global user.email $USER_MAIL
  - git config --global user.name $USER_NAME

# pipeline stages
stages:
  - execute

execute:
  stage: execute
  script:
    - make $TARGET