apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: stakater-control-reloader
  namespace: control
spec:
  releaseName: stakater-control-reloader
  chart:
    repository: https://stakater.github.io/stakater-charts/
    name: reloader
    version: 0.0.52
  values:
    reloader:
      watchGlobally: true
      deployment:
        resources:
          limits:
            cpu: "100m"
            memory: "512Mi"
          requests:
            cpu: "10m"
            memory: "128Mi"