apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: stakater-istio
  namespace: istio-system
spec:
  releaseName: stakater-istio
  chart:
    repository: https://storage.googleapis.com/istio-release/releases/1.4.2/charts/
    name: istio
    version: 1.4.2
  values:
    global:
      enableTracing: true
    mixer:
      telemetry:
        resources:
          requests:
            cpu: 100m
            memory: 500m
    sidecarInjectorWebhook:
      enabled: true
      rewriteAppHTTPProbe: true
    pilot:
      traceSampling: 100
    prometheus:
      enabled: false
    tracing:
      enabled: true
    grafana:
      enabled: false
    kiali:
      enabled: true