apiVersion: v1
data:
  tls.key: "BASE64_ENCODED_SEALED_SECRETS_TLS_KEY"
  tls.crt: "BASE64_ENCODED_SEALED_SECRETS_TLS_CRT"
kind: Secret
metadata:
  name: sealed-secrets-key
  namespace: security
  labels:
    sealedsecrets.bitnami.com/sealed-secrets-key: active
type: kubernetes.io/tls