apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: stakater-security-sealed-secrets
  namespace: security
spec:
  releaseName: stakater-security-sealed-secrets
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: sealed-secrets
    version: 1.5.0
  values:
    image:
      repository: quay.io/bitnami/sealed-secrets-controller
      tag: v0.9.4
      pullPolicy: IfNotPresent
    serviceAccount:
      create: true
      name: ""
    rbac:
      create: true
    secretName: "sealed-secrets-key" #The name of the TLS secret containing the key used to encrypt secrets
    crd:
      create: false
      keep: true
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi